/* Generated By:JJTree: Do not edit this line. build/xquery30/java/fr.lsv.xpparser/XParserVisitor.java */

package fr.lsv.xpparser;

public interface XParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
