/* Generated By:JJTree: Do not edit this line. build/xquery30/java/org.w3c.xqparser/XParserVisitor.java */
/*
This software or document includes material copied from or derived 
from the XPath/XQuery Applets (https://www.w3.org/2013/01/qt-applets/).
Copyright © 2013 W3C® (MIT, ERCIM, Keio, Beihang).
*/
package org.w3c.xqparser;

public interface XParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
